export const HUBSPOT_WEBHOOK_FETCH_TIMEOUT_CAP_MS = 4_500;
export const STAGE_NOTIFICATION_LEASE_MS = 60_000;
export const READINESS_NOTIFICATION_LEASE_MS = STAGE_NOTIFICATION_LEASE_MS;
export const READINESS_NOTIFICATION_MAX_ATTEMPTS = 3;
export const FALLBACK_NOTIFICATION_LEASE_MS = READINESS_NOTIFICATION_LEASE_MS;
export const FALLBACK_NOTIFICATION_MAX_ATTEMPTS = 3;
export const TERMINAL_DRIFT_NOTIFICATION_LEASE_MS =
  READINESS_NOTIFICATION_LEASE_MS;
export const TERMINAL_DRIFT_NOTIFICATION_MAX_ATTEMPTS = 3;
export const MAX_FUTURE_SKEW_MS = 300_000;
export const TERMINAL_TIE_WINDOW_MS = 300_000;
export const ENRICHMENT_FACT_MIN_CONFIDENCE = 0.2;
export const ENRICHMENT_FACT_MAX_AGE_DAYS = 30;
export const DEPLOYMENT_FACT_MAX_AGE_DAYS = 30;
export const READINESS_PENDING_SLA_HOURS = 24;

const MIN_STAGE_NOTIFICATION_LEASE_MS = HUBSPOT_WEBHOOK_FETCH_TIMEOUT_CAP_MS * 2;
const MIN_READINESS_NOTIFICATION_LEASE_MS =
  HUBSPOT_WEBHOOK_FETCH_TIMEOUT_CAP_MS * 2;

if (STAGE_NOTIFICATION_LEASE_MS < MIN_STAGE_NOTIFICATION_LEASE_MS) {
  throw new Error(
    `STAGE_NOTIFICATION_LEASE_MS must be at least ${MIN_STAGE_NOTIFICATION_LEASE_MS}ms`,
  );
}

if (READINESS_NOTIFICATION_LEASE_MS < MIN_READINESS_NOTIFICATION_LEASE_MS) {
  throw new Error(
    `READINESS_NOTIFICATION_LEASE_MS must be at least ${MIN_READINESS_NOTIFICATION_LEASE_MS}ms`,
  );
}

if (FALLBACK_NOTIFICATION_LEASE_MS < MIN_READINESS_NOTIFICATION_LEASE_MS) {
  throw new Error(
    `FALLBACK_NOTIFICATION_LEASE_MS must be at least ${MIN_READINESS_NOTIFICATION_LEASE_MS}ms`,
  );
}

if (TERMINAL_DRIFT_NOTIFICATION_LEASE_MS < MIN_READINESS_NOTIFICATION_LEASE_MS) {
  throw new Error(
    `TERMINAL_DRIFT_NOTIFICATION_LEASE_MS must be at least ${MIN_READINESS_NOTIFICATION_LEASE_MS}ms`,
  );
}

// ── Engagement attribution: hours-saved model assumptions (D9) ────────────
// Minutes a human would spend triaging+routing one inbound deal.
// Conservative (real times are usually higher) — under-claim a modeled number.
export const ASSUMED_TRIAGE_MIN = 8;
// Minutes to research+draft one outreach touch by hand.
export const ASSUMED_DRAFT_MIN = 20;
