export const HUBSPOT_WEBHOOK_FETCH_TIMEOUT_CAP_MS = 4_500;
export const STAGE_NOTIFICATION_LEASE_MS = 60_000;

const MIN_STAGE_NOTIFICATION_LEASE_MS = HUBSPOT_WEBHOOK_FETCH_TIMEOUT_CAP_MS * 2;

if (STAGE_NOTIFICATION_LEASE_MS < MIN_STAGE_NOTIFICATION_LEASE_MS) {
  throw new Error(
    `STAGE_NOTIFICATION_LEASE_MS must be at least ${MIN_STAGE_NOTIFICATION_LEASE_MS}ms`,
  );
}
